import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white dark:bg-gray-800 shadow-md p-4 border-b">
          <div className="max-w-7xl mx-auto flex justify-between items-center">
            <div className="flex space-x-6">
              <Link href="/" className="text-gray-700 hover:text-blue-500 font-medium">Home</Link>
              <Link href="/login" className="text-gray-700 hover:text-blue-500 font-medium">Login</Link>
              <Link href="/dashboard" className="text-gray-700 hover:text-blue-500 font-medium">Dashboard</Link>
              <Link href="/notifications" className="text-gray-700 hover:text-blue-500 font-medium">Notifications</Link>
              <Link href="/settings" className="text-gray-700 hover:text-blue-500 font-medium">Settings</Link>
              <Link href="/billing" className="text-gray-700 hover:text-blue-500 font-medium">Billing</Link>
              <Link href="/analytics" className="text-gray-700 hover:text-blue-500 font-medium">Analytics</Link>
            </div>
          </div>
        </nav>
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
